# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: false

# Setup
title:            Matias Levy-Hara
tagline:          'Portfolio'
description:      'A portfolio for Matias Levy-Hara'
url:              https://matiaslh.github.io
baseurl:          /

author:
  name:           'Matias Levy-Hara'
  url:            https://matiaslh.github.io

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jemoji